[package]
name = "fm_transmit"
version = "0.1.0"
edition = "2021"

[dependencies]
libhackrf = { path = ".." }

anyhow = "1.0.89"
clap = { version = "4.5.30", features = ["derive"] }
hound = "3.5.1"
itertools = "0.13.0"
num-complex = "0.4.6"
num-traits = "0.2.19"
